name: Issue
description: Report a bug or problem
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting an issue!**
        - Please search [existing issues](https://github.com/Frexxis/hyprod/issues?q=is%3Aissue) before submitting.
        - For questions or help, use [Discussions](https://github.com/Frexxis/hyprod/discussions) instead.

  - type: checkboxes
    attributes:
      label: "Before you submit"
      options:
        - label: I have read the [TROUBLESHOOTING.md](https://github.com/Frexxis/hyprod/blob/main/TROUBLESHOOTING.md) guide.
          required: true
        - label: I have updated to the latest version.
          required: false
        - label: I have updated system packages.
          required: false

  - type: textarea
    attributes:
      label: "Diagnostic info"
      description: "Run `./diagnose` in the repo directory and paste the result below."
      value: |
        <details><summary>Diagnose output</summary>

        ```
        <!-- Paste ./diagnose output here -->
        ```

        </details>
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Describe the issue"
      description: "What happened? What did you expect?"
      value: |
        **Description:**


        **Steps to reproduce:**
        1.
        2.
        3.

        <details><summary>Logs</summary>

        ```
        <!-- Paste relevant logs here -->
        ```

        </details>
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Acknowledgment
      options:
        - label: I understand that logs are essential for debugging.
          required: true
