name: Feature request
description: Suggest an idea for hyprod
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for the suggestion!**
        Please search [existing issues](https://github.com/Frexxis/hyprod/issues?q=is%3Aissue) before submitting.

  - type: textarea
    attributes:
      label: "What would you like to be added?"
      description: "Describe the feature - could be a new widget, behavior change, integration, etc."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "How will it help?"
      description: "Describe your use case and how this would improve your workflow."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Additional context"
      description: "Screenshots, mockups, or links to similar implementations."
